test_c2buf:
	gcc test_c2buf.c c2buf.c c2brush.c -lncurses -otest_c2buf

test_c2buf_ncurses:
	gcc test_c2buf_ncurses.c c2buf.c c2brush.c -lncurses -otest_c2buf_ncurses

.PHONY:	test_c2buf test_c2buf_ncurses
